# Racial Bias Reporter #
# Project Description: Web-app to allow victims of on-campus racial bias
# to report these incidents to their schools, and track the
# resolution.
# File Description: Helper class for the 'about' page
# Auto-Generated?: Auto-generated by rails
module AboutHelper
end
