# Racial Bias Reporter #
# Project Description: Web-app to allow victims of on-campus racial bias
# to report these incidents to their schools, and track the
# resolution.
# File Description: general application helper class
# Auto-Generated?: Auto-generated by rails
module ApplicationHelper
end
