# Racial Bias Reporter #
# Project Description: Web-app to allow victims of on-campus racial bias
# to report these incidents to their schools, and track the
# resolution.
# File Description: helper class for the schools pages
# Auto-Generated?: Auto-generated by rails
module SchoolsHelper 
end
