# Racial Bias Reporter #
# Project Description: Web-app to allow victims of on-campus racial bias
# to report these incidents to their schools, and track the
# resolution.
# File Description: controller class for the 'about' page
# Auto-Generated?: Auto-generated by rails

##
# A class representing a controller which handles HTTP requests relating to the about page.
class AboutController < ApplicationController
  ##
  # GET /about/index
  def index
  end
end

