# Racial Bias Reporter #
# Project Description: Web-app to allow victims of on-campus racial bias
# to report these incidents to their schools, and track the
# resolution.
# File Description: parent application controller class
# Auto-Generated?: Auto-generated by rails, lightly modified by me
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include TrackReportsHelper
  include FacultySessionsHelper
end
