# Racial Bias Reporter #
# Project Description: Web-app to allow victims of on-campus racial bias
# to report these incidents to their schools, and track the
# resolution.
# File Description: controller class for the homepage
# Auto-Generated?: Auto-generated by rails

##
# A class representing a controller which handles HTTP requests relating to the home page.
class HomeController < ApplicationController
  ##
  # GET /home/index
  def index
  end
end
